name: API Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman API Tests
        run: |
          newman run "./Postman/Collection.json.json" \
            -e "./Postman/Environment.json.postman_environment (2).json" \
            -d "./Postman/data.csv"
